<?php

namespace Tests\Unit;

use App\Exceptions\InvalidDateException;
use App\Validators\DateValidator;
use PHPUnit\Framework\TestCase;

/**
 * @package Tests
 * @group unit
 * @group ready
 */
class ValidatorsTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testDateValidateFormat()
    {
        $this->assertTrue(DateValidator::validateFormat('20210830T19:23:59'));
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testDateValidator()
    {
        $this->assertTrue(DateValidator::validateDate('20210830T19:23:59'));
    }

    /**
     * @throws \App\Exceptions\InvalidDateException
     */
    public function testDateValidatorException()
    {
        $this->expectException(InvalidDateException::class);
        DateValidator::validateDate('20211335T25:00:11');
    }
}
